clear all
crediti = input('inserire array di crediti degli esami conseguiti: ')
voti = input('inserire array di voti degli esami conseguiti: ')
pesi = sum(crediti);
mediana = median(voti);
media = sum(voti)/max(size(voti));
media_pesata = sum(voti.*crediti)/pesi;

fprintf(['la mediana è \t\t%1.2f\n' ...
    'la media è \t\t%1.2f\n' ...
    'la media pesata è \t%1.2f\n' ...
    'il voto massimo è \t%1.2f\n' ...
    'il voto minimo è \t%1.2f\n'], mediana, media, media_pesata, max(voti), min(voti))
